export { default as activitiesAPI } from './activities/activities.api'
export { default as coursesAPI } from './courses/courses.api'
export { default as authAPI } from './auth/auth.api'
export { default as classesAPI } from './classes/classes.api'
export { default as courseStudentsAPI } from './course-student/course-studen.api'
export { default as studentsAPI } from './students/students.api'
export { default as topicsAPI } from './topic/topic.api'
export { default as usersAPI } from './user/user.api'
