export { default as ActivitiesSlide } from './activities/ActivitiesSlide.jsx'
export { default as ClasseSlide } from './classes/ClasseSlide.jsx'
export { default as CoursesSlide } from './courses/CoursesSlide.jsx'
export { default as NewsSlide } from './news/NewsSlide.jsx'
export { default as StudentsSlide } from './students/StudentSlide.jsx'
