export { default as HomeStudent } from './home/Home.jsx'
export { default as ClassStudent } from './class/Class.jsx'
export { default as ActivitiesStudent } from './activities/Activities.jsx'
export { default as Completed } from './tabs/activities/Completed.jsx'
export { default as Overdue } from './tabs/activities/Overdue.jsx'
export { default as Pending } from './tabs/activities/Pending.jsx'
export { default as QuizzCodeFeedback } from './feedbacks/QuizzCodeFeedback.jsx'
